#!/bin/bash
#获取shell文件所在的绝对路径
current_path=$(pwd)
tmp_path=$(dirname $0)
cd $tmp_path
shell_path=$(pwd)
cd $current_path

#发布应用的url地址
pulish_url="http://192.168.21.89"

#工程绝对路径
project_path=/Applications/XAMPP/xamppfiles/htdocs/focus-app/apptemp

#判断是否执行过ipa-build脚本
rm -rf $project_path/$1
mkdir $project_path/$1

cp $project_path/$2 $project_path/$1

rm -rf $project_path/$2

ls $project_path/$1/$2 &>/dev/null
rtnValue=$?
if [ $rtnValue != 0 ];then
		echo "Error!! No ipa files exists.Please run the \"ipa-build\" shell script first"
			exit
			fi

#切换到tmp文件夹
cd /Applications/XAMPP/xamppfiles/htdocs/focus-app/apptemp/tmp
#创建临时文件夹
tmpfoldername=ipa_tmp
if [ -d ./${tmpfoldername} ];then
		rm -rf ${tmpfoldername}
		fi
		mkdir ${tmpfoldername}

		cd ${tmpfoldername}
#拷贝ipa到临时文件夹中
        cp $project_path/$1/$2  ./tmp.zip
#将ipa解压
		unzip tmp.zip
#app文件中Info.plist文件路径
		app_infoplist_path=$(pwd)/Payload/*.app/Info.plist
#取版本号
		bundleShortVersion=$(/usr/libexec/PlistBuddy -c "print CFBundleShortVersionString" ${app_infoplist_path})
#取build值
		bundleVersion=$(/usr/libexec/PlistBuddy -c "print CFBundleVersion" ${app_infoplist_path})
#取bundleIdentifier
		bundleIdentifier=$(/usr/libexec/PlistBuddy -c "print CFBundleIdentifier" ${app_infoplist_path})
#取CFBundleName
		target_name=$(/usr/libexec/PlistBuddy -c "print CFBundleName" ${app_infoplist_path})
#取CFBundleDisplayName
		display_name=$(/usr/libexec/PlistBuddy -c "print CFBundleDisplayName" ${app_infoplist_path})

#删除临时文件夹
cd ..
#rm -rf ${tmpfoldername}
rm -rf *

#进入到工程build路径下
cd $project_path/$1

#显示名称
ipa_name="${display_name}"


#if [ -d ./$target_name ];then
#		rm -rf $target_name
#		fi
#		mkdir $target_name
#拷贝ipa
#		cp ./*.ipa ./$target_name/${target_name}.ipa
#		cp ../Icon@2x.png ./$target_name/${target_name}_logo.png
#		cd $target_name

#ipa下载url
#ipa_download_url=${pulish_url}/auto-ipa-build/${target_name}.ipa

ipa_download_url=${pulish_url}/new_app/pub_ipa/$2

#生成plist文件
cat << EOF > $3.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
	<key>items</key>
	  <array>
		<dict>
		 <key>assets</key>
		  <array>
		   <dict>
		    <key>kind</key>
		    <string>software-package</string>
		    <key>url</key>
		    <string>${ipa_download_url}</string>
		  </dict>
        </array>
        <key>metadata</key>
         <dict>
          <key>bundle-identifier</key>
          <string>${bundleIdentifier}</string>
          <key>bundle-version</key>
          <string>${bundleVersion}</string>
          <key>kind</key>
          <string>software</string>
          <key>title</key>
          <string>${ipa_name}</string>
         </dict>
      </dict>
   </array>
 </dict>
</plist>

EOF

cp -r /Applications/XAMPP/xamppfiles/htdocs/focus-app/apptemp/$1/$2  /Applications/XAMPP/xamppfiles/htdocs/focus-app/new_app/pub_ipa
cp -r /Applications/XAMPP/xamppfiles/htdocs/focus-app/apptemp/$1/$3.plist /Applications/XAMPP/xamppfiles/htdocs/focus-app/new_app/pub_plist





